import os

TRADING_MODE = os.environ.get("TRADING_MODE", "paper")

ALPACA_PAPER_KEY = os.environ.get("ALPACA_PAPER_KEY", "")
ALPACA_PAPER_SECRET = os.environ.get("ALPACA_PAPER_SECRET", "")
ALPACA_PAPER_URL = "https://paper-api.alpaca.markets"

ALPACA_LIVE_KEY = os.environ.get("ALPACA_LIVE_KEY", "")
ALPACA_LIVE_SECRET = os.environ.get("ALPACA_LIVE_SECRET", "")
ALPACA_LIVE_URL = "https://api.alpaca.markets"

DISCORD_WEBHOOK_TRADE_ALERTS = os.environ.get("DISCORD_WEBHOOK_TRADE_ALERTS", "")
DISCORD_WEBHOOK_SYSTEM_STATUS = os.environ.get("DISCORD_WEBHOOK_SYSTEM_STATUS", "")
DISCORD_WEBHOOK_DAILY_SUMMARY = os.environ.get("DISCORD_WEBHOOK_DAILY_SUMMARY", "")
DISCORD_WEBHOOK_PAPER_TRADES = os.environ.get("DISCORD_WEBHOOK_PAPER_TRADES", "")
DISCORD_WEBHOOK_LIVE_TRADES = os.environ.get("DISCORD_WEBHOOK_LIVE_TRADES", "")
DISCORD_WEBHOOK_MARKET_HOURS = os.environ.get("DISCORD_WEBHOOK_MARKET_HOURS", "")

DISCORD_BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN", "")
DISCORD_USER_ID = os.environ.get("DISCORD_USER_ID", "")

MODE_SWITCH_PASSWORD = os.environ.get("MODE_SWITCH_PASSWORD", "changeme")
LIVE_CONFIRM_PHRASE = "I CONFIRM LIVE TRADING"

MAX_RISK_PER_TRADE_PCT = 1.0
MAX_DAILY_LOSS_PCT = 3.0
MAX_TRADES_PER_DAY = 5
WEEKLY_DRAWDOWN_HALT_PCT = 7.0